version: 2.1
jobs:
  test:
    docker:
      - image: debian:stretch
    steps:
      - run:
          name: Test bored
          command: ./bored

      - run:
          name: Test bored config
          command: echo -e "c\n1" | ./boredconf; echo -e "n\nTest boredbutton?\nIt is great fun." | ./boredconf
workflows:
  version: 2
  test:
    jobs:
      - test